region             = "us-east-1"
vpc_cidr_block     = "10.0.0.0/16"
public_subnet_cidr = "10.0.1.0/24"
private_subnet_cidr = "10.0.2.0/24"
availability_zone  = "us-east-1a"
project_name       = "terraform-ec2-vpc"
instance_type      = "t2.micro"
ami_id             = "ami-0c55b159cbfafe1f0"  # Amazon Linux 2 AMI (adjust as needed)
key_name           = "my-key-pair"  # Replace with your key pair name or remove if not needed